### ISSUE TITLE
ModuleNotFoundError: No module named 'curvelops.plots'

### ISSUE THREAD

**Issue by sireeshgit** [PyLops/curvelops#18]
Hello,

Thank you for making the Curvelops available for everyone. Great piece of code.
I think there is a bug in the Desmystifying_Curvelets.ipynb notebook.
When try to run the from curvelops.plot import cureshow I get the error in the 
subject.

**Comment by cako** [comment]
Hi @sireeshgit, thanks for reporting this! Please check if your curvelops version is before v0.22. If so, you need to upgrade to at least v0.22. I just released a version with a bugfix for the subpackage plot (thanks for the bug report!) so you would install that one:

```bash
python3 -m pip install git+https://github.com/PyLops/curvelops@0.23
```

Let me know if you still have issues with this version.

**Comment by sireeshgit** [comment]
> Hi @sireeshgit, thanks for reporting this! Please check if your curvelops version is before v0.22. If so, you need to upgrade to at least v0.22. I just released a version with a bugfix for the subpackage plot (thanks for the bug report!) so you would install that one:
> 
> ```shell
> python3 -m pip install git+https://github.com/PyLops/curvelops@0.23
> ```
> 
> Let me know if you still have issues with this version.

Hi @cako Still seeing the same issue.

![Screenshot 2023-03-25 001803](https://user-images.githubusercontent.com/71159798/227697897-a9ae3870-df06-485d-b21b-bf00ad37f559.jpg)

**Comment by cako** [comment]
Hi @sireeshgit, I have not been able to reproduce, unfortunately. Could you try the following steps:

```bash
$ virtualenv venv39 --python=python3.9
$ source venv39/bin/activate
(venv39) $ which python3  # ensure it is the venv39 python3
/path/to/venv39/bin/python3
(venv39) $ export FFTW=/path/to/fftw-2.1.5 && export FDCT=/path/to/CurveLab-2.1.3
(venv39) $ python3
Python 3.9.16 (main, Dec  7 2022, 01:12:08) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from curvelops.plot import curveshow
>>> from curvelops import curveshow  # alternative
>>> import numpy as np
>>> curveshow([[np.array([[0]])]])
[(<Figure size 500x500 with 1 Axes>, <Axes: >)]
```

**Comment by cako** [comment]
@mrava87 could you to reproduce this?

**Comment by mrava87** [comment]
I can try tomrrow, sure 😀

**Comment by sireeshgit** [comment]
Interesting. I had to install numpy and curvelops in the venv but ran into a pip issue with no simple fix. 
(venv39) (base) sireeshunix@Sireesh:~$ pip3 install numpy
Traceback (most recent call last):
  File "/home/sireeshunix/venv39/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
  File "/home/sireeshunix/venv39/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/sireeshunix/venv39/lib/python3.9/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/sireeshunix/venv39/lib/python3.9/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/sireeshunix/venv39/lib/python3.9/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.exceptions import CommandError
  File "/home/sireeshunix/venv39/lib/python3.9/site-packages/pip/_internal/exceptions.py", line 10, in <module>
    from pip._vendor.six import iteritems
ModuleNotFoundError: No module named 'pip._vendor.six'

**Comment by cako** [comment]
It seems some sort of environment configuration issue. See the following resources: [1](https://github.com/pypa/pipenv/issues/4804), [2](https://askubuntu.com/questions/1351160/modulenotfounderror-no-module-named-pip-vendor-six), [3](https://bnikolic.co.uk/blog/python/pip/2022/02/21/vendored-six.html).

I would try to repeat the above steps with a virtual environment using the same version of Python as your global one. In my case that was Python 3.9, but yours might be 3.8 or older.

**Comment by sireeshgit** [comment]
> It seems some sort of environment configuration issue. See the following resources: [1](https://github.com/pypa/pipenv/issues/4804), [2](https://askubuntu.com/questions/1351160/modulenotfounderror-no-module-named-pip-vendor-six), [3](https://bnikolic.co.uk/blog/python/pip/2022/02/21/vendored-six.html).
> 
> I would try to repeat the above steps with a virtual environment using the same version of Python as your global one. In my case that was Python 3.9, but yours might be 3.8 or older.

Hi @cako 
My python version is also 3.9

![image](https://user-images.githubusercontent.com/71159798/227738460-94a4ae6e-d95a-4ed7-8d70-425638ccebc9.png)

**Comment by cako** [comment]
Hi @sireeshgit, if that's the case, I would try some of the suggestions in the resources that I shared above. I will also wait for @mrava87 to chime in whenever he has a chance.

**Comment by sireeshgit** [comment]
> Hi @sireeshgit, if that's the case, I would try some of the suggestions in the resources that I shared above. I will also wait for @mrava87 to chime in whenever he has a chance.

I was address the issue with 'pip._vendor.six' but I got another errror ImportError: cannot import name randbits
while importing numpy. I think there is a random.py which is conflict with some other package. 

I will wait for @mrava87 as well. So far I am trying to run this on linux. I will try with my anaconda on windows side. I will have to intsall pylops on curvelop again.

**Comment by cako** [comment]
If you are not even able to install numpy, it seems like an environment issue at this point. By the way, I am not sure CurveLab can be compiled on Windows, at least I have never tried. I would stick to Linux for now since you have access to it. Otherwise try installing through WSL2.

**Comment by mrava87** [comment]
I just tried, and it works for me. 

What I did:
- remove current version of `curvelops` I had in my env
- run this
```
export CC=/usr/bin/gcc-4.8
export CXX=/usr/bin/g++-4.8
export FFTW=${PWD}/fftw-2.1.5
export FDCT=${PWD}/CurveLab-2.1.3
git clone https://github.com/PyLops/curvelops.git curvelops_310
cd curvelops_310
python3 -m pip install -e .
```
- run `python -c 'import curvelops as cl; print(cl.__version__); ` -> 0.24.dev1+g1333ae5
- run @cako commands above and I also get `[(<Figure size 500x500 with 1 Axes>, <Axes: >)]`

**Comment by cako** [comment]
Great, thanks @mrava87. Let us know if you can reproduce his steps @sireeshgit

**Comment by sireeshgit** [comment]
Great. That worked. Thanks @cako and @mrava87
